### ISSUE TITLE
#200

### ISSUE THREAD

**Issue by Potato1682** [PeyaPeyaPeyang/HomePage#2]
なんか踏めたので立てます。

**Comment by Potato1682** [comment]
こちらで確認してみましたが、確かにそうでした。ごめんなさい…
代わりに、パフォーマンス、ユーザー補助の観点で100点を目指す方に妥協しませんか？
CSS filterプロパティーをコード内で使用されていることから、IE11など多少古いブラウザーのサポートはされていないようですので、ある程度の最適化を施す余地はあるはずです。

**Comment by PeyaPeyaPeyang** [comment]
LGTM
